sudo: false
language: php
php:
  - '5.5'
before_install:
  - composer self-update
script: 
  - composer config -g repositories.private composer $COMPOSER_REPOSITORY_URL
  - composer install
deploy:
  - provider: opsworks
    access_key_id: AKIAI65HYMCAT2AOFKUQ
    secret_access_key:
      secure: UUJ/T1qVO7op4NBkLb2omw/N3XNWgCwz4p58XTbCBVO7FVSuBR6yF533OPlnk55ToCvRuJiDJ7GDGfKe42fwuqmXCwNoARAZeLcGnxPyyxatz4EWuC3UltPS9TWPAg83nDS23AQ3wqqfU5C/JwlQ6XMhSk8YK5RqmxXcumo/csyIZfs3YUrrvfx7RQwPUXggRfsyHSobSEe3W4eqWq1PGSMicVtUa7fQvk6jtaNWgkNP/br1t7pOy61/w3OK4DY8kSeHukoXjkDQQzrsu3BUdKNrI/tfhCCXTy++yFwFx54ZBnOUsqzmNOVBJaUWNntTEwQUPOtvvohW5I9f10aEPr45o57xwRJ9dEMb+VHlRjNrkrUvjJoySV1+oa/N1SguIwzoLoeREGq4Wyutnr4YE56z4oEYiGxqvr338A8+DhtCSgzQDXI5kSq63X3c8gk8r/l8vLs1wWBNp1TrAwt9kaXx2xD4EpZ1M1Mbo79GC7Jmg/S1hUiyQXYmbjc2f4nT71opQwP8npcD0BifLW0mFZ4tdWBA1cxR5IqOH452eXmW3BdIGxXcilAbcvLK1QkdxWLx19KimGWYyGDI3UCXRzfrMSo5HDwmacam2WmWq6nwEsJsSSH1sIST6ozE+Mh6j00K1sm85uVaHKhQ6gu//SUm0HhMdyCBEt3LnrgBQVQ=
    app-id: 4a3a7eea-96ba-4f54-9179-2d5f5193fee2
  - provider: opsworks
    access_key_id: AKIAI65HYMCAT2AOFKUQ
    secret_access_key:
      secure: UUJ/T1qVO7op4NBkLb2omw/N3XNWgCwz4p58XTbCBVO7FVSuBR6yF533OPlnk55ToCvRuJiDJ7GDGfKe42fwuqmXCwNoARAZeLcGnxPyyxatz4EWuC3UltPS9TWPAg83nDS23AQ3wqqfU5C/JwlQ6XMhSk8YK5RqmxXcumo/csyIZfs3YUrrvfx7RQwPUXggRfsyHSobSEe3W4eqWq1PGSMicVtUa7fQvk6jtaNWgkNP/br1t7pOy61/w3OK4DY8kSeHukoXjkDQQzrsu3BUdKNrI/tfhCCXTy++yFwFx54ZBnOUsqzmNOVBJaUWNntTEwQUPOtvvohW5I9f10aEPr45o57xwRJ9dEMb+VHlRjNrkrUvjJoySV1+oa/N1SguIwzoLoeREGq4Wyutnr4YE56z4oEYiGxqvr338A8+DhtCSgzQDXI5kSq63X3c8gk8r/l8vLs1wWBNp1TrAwt9kaXx2xD4EpZ1M1Mbo79GC7Jmg/S1hUiyQXYmbjc2f4nT71opQwP8npcD0BifLW0mFZ4tdWBA1cxR5IqOH452eXmW3BdIGxXcilAbcvLK1QkdxWLx19KimGWYyGDI3UCXRzfrMSo5HDwmacam2WmWq6nwEsJsSSH1sIST6ozE+Mh6j00K1sm85uVaHKhQ6gu//SUm0HhMdyCBEt3LnrgBQVQ=
    app-id: ab4953b2-fb98-4ea2-ae61-d5ed88d5bb12
    on: staging
